Update verilog_verification.yml

diff --git a/.github/workflows/verilog_verification.yml b/.github/workflows/verilog_verification.yml
--- a/.github/workflows/verilog_verification.yml
+++ b/.github/workflows/verilog_verification.yml
@@ -148,6 +148,12 @@ jobs:
       run: |
         git config --global user.name "github-actions[bot]"
         git config --global user.email "github-actions@github.com"
+        if [ -f "result/success/success_per.txt" ]; then
+          mv result/success/success_per.txt result/
+        else
+          echo "⚠️ Error: success_per.txt 파일이 생성되지 않았습니다!"
+          exit 1
+        fi
         git add result/success_per.txt # verilog_output.txt를 github에 추가
         git commit -m "Update success_per.txt (auto)" # 변경 사항이 있을 경우 commit
         git push --force
